// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlrkiwnmissvmiupaena.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impscmtpd25taXNzdm1pdXBhZW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Mjk1ODEsImV4cCI6MjA1OTMwNTU4MX0.Kdfzx0fyPR_5b2eAXA_2ATozR1sLlLajfu1lITmApVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);